MILVUS_HOST = 'localhost'
MILVUS_PORT = '19530'
COLLECTION_NAME = 'faces'
FACE_RECOGNITION_TOLERANCE = 0.6
DUPLICATE_FACE_THRESHOLD = 0.5
CAMERA_INDEX = 0
CAMERA_INIT_DELAY = 0.5
MAX_LOGIN_ATTEMPTS = 6

FLASK_HOST = '127.0.0.1'
FLASK_PORT = 5000
FLASK_DEBUG = True
